
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5433 #cambio de puerto en postgres

development:
  <<: *default
  database: my_favorite_development

production:
  <<: *default
  database: my_favorite_production
  username: my_favorite
  password: <%= ENV['MY_FAVORITE_DATABASE_PASSWORD'] %>
